Change Port
KateChoo/taipei-day-trip-website pull request #1
Opened 2021-04-19 04:23 UTC by KateChoo

XD by Kate Choo

2021-04-19 04:33 UTC, cwpeng requested changes
在 GitHub 上的 main 分支看起沒有被動到，你可以確認看看。

請設定 main 分支的管理保護規則。

2021-04-19 12:12 UTC, KateChoo commented
> 在 GitHub 上的 main 分支看起沒有被動到，你可以確認看看。
> 
> 請設定 main 分支的管理保護規則。

應該...有去設定了...再請老師確認一下

2021-04-19 12:14 UTC, cwpeng commented
請再要求我 review 一次，我才有辦法幫你 approve

2021-04-19 12:22 UTC, cwpeng approved these changes
OK.

2021-04-20 08:52 UTC, cwpeng commented
記得先 merge pull request 哦，這樣算一件事情告一段落，後續開發到下個階段，可以再重新發 pull request

2021-04-20 13:39 UTC, merged