Develop
KateChoo/taipei-day-trip-website pull request #2
Opened 2021-04-26 16:25 UTC by KateChoo

http://54.249.216.135:3000/api/attractions?page=0&keyword=藝術
http://54.249.216.135:3000/api/attractions?page=1
http://54.249.216.135:3000/api/attraction/100

2021-04-26 16:41 UTC, cwpeng requested changes
有些需要調整的部份如下：
1. 我們的 page 必須由 0 開始起算，所以以下這個網址要是我們的第一頁：
http://54.249.216.135:3000/api/attractions?page=0
2. 單一景點的資料，似乎沒有給出所有的圖片，我們取得景點資料都要包含所有的圖片：
http://54.249.216.135:3000/api/attraction/1
3. 搜尋沒有發生作用，會出現完全無關的結果，例如：
http://54.249.216.135:3000/api/attractions?page=1&keyword=步道

2021-04-27 09:15 UTC, KateChoo commented
> 有些需要調整的部份如下：
> 
> 1. 我們的 page 必須由 0 開始起算，所以以下這個網址要是我們的第一頁：
>    http://54.249.216.135:3000/api/attractions?page=0
> 2. 單一景點的資料，似乎沒有給出所有的圖片，我們取得景點資料都要包含所有的圖片：
>    http://54.249.216.135:3000/api/attraction/1
> 3. 搜尋沒有發生作用，會出現完全無關的結果，例如：
>    [http://54.249.216.135:3000/api/attractions?page=1&keyword=步道](http://54.249.216.135:3000/api/attractions?page=1&keyword=%E6%AD%A5%E9%81%93)

再請老師看看～

2021-04-27 09:17 UTC, cwpeng approved these changes
OK. Good Fix.

2021-05-04 07:28 UTC, cwpeng commented
記得要把上一週的 Pull Request 先 Merge 哦

2021-05-06 01:58 UTC, closed without merging