Develop
KateChoo/taipei-day-trip-website pull request #3
Opened 2021-05-06 02:16 UTC by KateChoo

＃＃＃第三週＃＃＃
邱鴻娟
http://54.249.216.135:3000/
http://54.249.216.135:3000/attraction/5

彭彭老師
我第二週keywords那裡不知為何只scroll第一頁之後便是無相關資訊
還在處理
第三週倒是初步先完成了

第一頁的keyword似乎沒問題
<img width="1269" alt="截圖 2021-05-06 上午10 11 06" src="https://user-images.githubusercontent.com/18051691/117232369-9299be80-ae53-11eb-9c31-c2246211268a.png">
再滑就變成主頁資訊等非相關資訊
<img width="1244" alt="截圖 2021-05-06 上午10 11 40" src="https://user-images.githubusercontent.com/18051691/117232476-d096e280-ae53-11eb-8ef5-4c261a335807.png">

2021-05-06 14:57 UTC, cwpeng requested changes
看起來第二週和第三週的進度都完成七成，但都還沒到可以過關的程度，首先是手機的版面看起來都還沒處理完如下，其他的細節明天剛好要見面，我們把握時間把所有事情都做完哦 ~

2021-05-08 04:28 UTC, KateChoo commented
應該暫時可以見人了ＸＤ

邱鴻娟
http://54.249.216.135:3000/
http://54.249.216.135:3000/attraction/5

再請老師看看～～

2021-05-08 05:44 UTC, cwpeng approved these changes
好哦，辛苦了，沒問題哦，這樣就可以了，替你高興 :)

我覺得隨時都可以素顏見人很 OK 的呀 XDDDD

2021-05-08 06:24 UTC, KateChoo commented
啊哈哈
謝謝老師ＸＤ

2021-05-08 09:54 UTC, closed without merging